name: Build Distribution

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        default: 'main'
        type: string
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up NPM
        uses: actions/setup-node@v4
      - run: npm ci
      - name: Update package.json
        run:  npm version from-git --no-git-tag-version
      - name: Build dist
        run: |
          rm -rf dist/*
          npm run build
      - name: Commit updated assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[BOT] Build distribution assets for ${{ github.ref_name }}"
          branch: ${{ inputs.branch || 'main' }}
          file_pattern: "package.json dist/**"