name: Build dist

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        default: 'main'
        type: string
  workflow_run:
    workflows: [ 'Test' ]
    types: [ completed ]
    branches:
      - main

permissions:
  contents: write

jobs:
  build-dist:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up NPM
        uses: actions/setup-node@v4
      - run: npm ci
      - name: Build dist
        run: npm run build
      - name: Commit updated assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[BOT] Build distribution assets"
          branch: ${{ inputs.branch || 'main' }}
          file_pattern: "dist/**"