name: Checks

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    files:
      - 'src/**/*.ts'
      - 'tests/**/*.ts'
      - '*.json'
      - '*.config.js'
      - '.github/workflows/checks.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: ['18', '20', '22', 'latest']
        check: ['biome', 'eslint', 'jest', 'oxlint']
        include:
          - check: 'biome'
            params: 'ci --reporter=github'
        exclude:
          - node: '18'
            check: 'jest'

    name: Run ${{ matrix.check }} on node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up NPM
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - name: Check code
        run: npx ${{ matrix.check }} ${{ matrix.params  || '' }}