name: Lint Assets

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    files:
      - 'src/**/*.ts'
      - 'tests/**/*.ts'
      - 'jest.config.json'
      - 'tsconfig.json'
      - '.github/workflows/test.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up NPM
        uses: actions/setup-node@v4
      - run: npm ci
      - name: Test code
        run: npm run test