name: "Update Changelog"

on:
  workflow_run:
    workflows: [ 'Publish to NPM' ]
    types: [ completed ]
    branches:
      - main

permissions:
  contents: write

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: laravel/.github/.github/workflows/update-changelog.yml@main